# Generated by Django 4.2.7 on 2025-09-05 21:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('website', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(choices=[('startup', 'Startup (1-10)'), ('small', 'Small (11-50)'), ('medium', 'Medium (51-200)'), ('large', 'Large (201-1000)'), ('enterprise', 'Enterprise (1000+)'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('linkedin_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('linkedin', 'LinkedIn'), ('twitter', 'Twitter'), ('facebook', 'Facebook'), ('other', 'Other')], max_length=20)),
                ('value', models.CharField(max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='companies.company')),
            ],
            options={
                'verbose_name': 'Company Contact',
                'verbose_name_plural': 'Company Contacts',
                'ordering': ['-is_primary', 'contact_type'],
                'unique_together': {('company', 'contact_type', 'value')},
            },
        ),
    ]
